### ISSUE TITLE
Firefox - Error: Mismatched anonymous define() module

### ISSUE THREAD

**Issue by atomotic** [UniversalViewer/uv-app-starter#3] opened 2018-02-19 21:00 UTC
i got this error with firefox (i'm not pasting the full message)
with chrome is working right

```
Error: Mismatched anonymous define() module
http://requirejs.org/docs/errors.html#mismatch uv.js:1:1984
```

should i try to downgrade universalviewer? 
the linked example https://sophiedixon.github.io/3d-portfolio/ i see that is using uv `3.0.14` and is working with FF

**Comment by edsilv** [comment] 2018-02-20 11:30
Which version of FF is that example working in for you? I'm on 58.0.1 and it's got the same error.

I'm seeing this problem back to UV v3.0.10, before which iiif-gallery stops working.

I've created a test page here: https://universalviewer.io/examples/portfolio.html

After comparing this with the regular examples I narrowed the problem down to including iiif-gallery in the page. If this is commented out, the issue goes away.

So it's something about iiif-gallery that's causing it (https://github.com/edsilv/iiif-gallery). 

Here's the requirejs page explaining the error: 

http://requirejs.org/docs/errors.html

iiif-gallery isn't using requirejs though... Confusing.

**Comment by atomotic** [comment] 2018-02-22 07:48
i have firefox 58.0.2, and yes, also the example 3d-portfolio is not fully working:  
it seems to me that the error is returned on the first loaded manifest of the collection, when clicking the second manifest the viewer works

**Comment by edsilv** [comment] 2018-02-22 10:15
Yep, that's what I'm seeing too. My theory is that it's happening when the UV is using require.js to load the dependencies for the current extension for the first time, e.g. Virtex for 3D, or OpenSeadragon for images. I tested it for images and it showed the same error.

There's something about iiif-gallery that's intefering with require.js I think...

First I'd like to update iiif-gallery to the latest stencil code and see if that magically fixes it. Then I'll try to create as simple a test harness as I can to reproduce it. If that succeeds, I've then got something to show the stencil team.

**Comment by edsilv** [comment] 2018-03-04 21:42
@atomotic I've managed to reproduce the issue in a test harness and have submitted a bug report here: https://github.com/ionic-team/stencil/issues/594
For now, the latest version (0.0.10) of iiif-gallery has a hacked dist file to prevent this issue.

**Comment by atomotic** [comment] 2018-03-05 23:08
where should i upgrade iiif-gallery in uv-app-starter?  
i tried upgrade only `universalviewer@3.0.22`

this my npm list
```
uv-app-starter@0.0.1 /Users/rfl/Documents/VAGUE/uv-app-starter
├─┬ biiif-cli@0.0.13
│ ├─┬ biiif@0.1.11
│ │ ├── chalk@2.3.1 deduped
│ │ ├─┬ glob@7.1.2
│ │ │ ├── fs.realpath@1.0.0
│ │ │ ├─┬ inflight@1.0.6
│ │ │ │ ├── once@1.4.0 deduped
│ │ │ │ └── wrappy@1.0.2
│ │ │ ├── inherits@2.0.3
│ │ │ ├─┬ minimatch@3.0.4
│ │ │ │ └─┬ brace-expansion@1.1.11
│ │ │ │   ├── balanced-match@1.0.0
│ │ │ │   └── concat-map@0.0.1
│ │ │ ├─┬ once@1.4.0
│ │ │ │ └── wrappy@1.0.2 deduped
│ │ │ └── path-is-absolute@1.0.1
│ │ ├─┬ js-yaml@3.10.0
│ │ │ ├─┬ argparse@1.0.10
│ │ │ │ └── sprintf-js@1.0.3
│ │ │ └── esprima@4.0.0
│ │ └── url-join@2.0.5
│ ├─┬ chalk@2.3.1
│ │ ├─┬ ansi-styles@3.2.0
│ │ │ └─┬ color-convert@1.9.1
│ │ │   └── color-name@1.1.3
│ │ ├── escape-string-regexp@1.0.5
│ │ └─┬ supports-color@5.2.0
│ │   └── has-flag@3.0.0
│ └── commander@2.14.1
├─┬ http-server@0.10.0
│ ├── colors@1.0.3
│ ├── corser@2.0.1
│ ├─┬ ecstatic@2.2.1
│ │ ├── he@1.1.1
│ │ ├── mime@1.6.0
│ │ ├── minimist@1.2.0
│ │ └── url-join@2.0.5 deduped
│ ├─┬ http-proxy@1.16.2
│ │ ├── eventemitter3@1.2.0
│ │ └── requires-port@1.0.0
│ ├── opener@1.4.3
│ ├─┬ optimist@0.6.1
│ │ ├── minimist@0.0.10
│ │ └── wordwrap@0.0.3
│ ├─┬ portfinder@1.0.13
│ │ ├── async@1.5.2
│ │ ├─┬ debug@2.6.9
│ │ │ └── ms@2.0.0
│ │ └─┬ mkdirp@0.5.1
│ │   └── minimist@0.0.8
│ └─┬ union@0.4.6
│   └── qs@2.3.3
└── universalviewer@3.0.22
```

thanks

**Comment by edsilv** [comment] 2018-03-06 13:31
It's being pulled in from unpkg.com here: https://github.com/UniversalViewer/uv-app-starter/blob/gh-pages/index.html#L11
There's no `@version`  specified in the url, so you should get the latest code.

**Comment by atomotic** [comment] 2018-03-11 21:42
actually, i'm still getting the error in FF
i've put here the sample collection i'm working with https://docuver.se/uv-app-starter

on a separate note, also thumbs are not working, i'm trying to debug, maybe a new ticket will follow https://docuver.se/uv-app-starter/collection/vague-21/

thanks!

**Comment by edsilv** [comment] 2018-03-11 22:31
I'm seeing one thumbnail in FF 58.0.2. The generated index.json thumbnail urls resolve ok - tried testing on localhost in iiif-gallery but getting cors errors. If you enable cors I can try to debug.

**Comment by atomotic** [comment] 2018-03-11 22:44
enabled now on https://docuver.se/uv-app-starter

**Comment by edsilv** [comment] 2018-03-12 11:22
So when testing in the iiif-gallery demo page with that manifest I'm seeing all thumbnails appear in Firefox, but when iiif-gallery is used in a page with the UV it's only creating one thumbnail... I've tried using uv.js instead of manifold.bundle.js in the iiif-gallery example, but no difference, it still works.
So the UV must be doing something else that's effecting it for your specific manifest in Firefox?
Other manifests are fine. Really weird.

I've added some notes to iiif-gallery btw: https://github.com/edsilv/iiif-gallery/blob/master/notes.md

I think the only thing I can do is publish a new version of iiif-gallery that console.logs everything and try to get to the bottom of it that way. I'm unlikely to have time this week, so it will have to be another weekend thing.

**Comment by edsilv** [comment] 2018-03-23 18:02
BTW, it looks like someone has been assigned to https://github.com/ionic-team/stencil/issues/594#issuecomment-370479069

**Comment by edsilv** [comment] 2018-04-28 14:50
Hi,

https://github.com/ionic-team/stencil/issues/594#issuecomment-384676034 has been fixed.

I've published v0.0.13 of iiif-gallery which uses stencil v0.7.27-4. This appears to be fine in Firefox now, e.g:

https://sophiedixon.github.io/3d-portfolio/

Regarding your thumbnail issue. I think we're not seeing any thumbnails for https://docuver.se/uv-app-starter/collection/vague-21/index.json because biiif was generating a `sequence` when it shouldn't have been for a IIIF v3 manifest. I've updated it since and published a test manifest here:

https://edsilv.github.io/biiif-workshop/collection/index.json

This is working in iiif-gallery. Please update your version of biiif-cli to v0.0.17 and re-publish your collection.

BTW, if you don't include a thumb.jpg biiif will now generate thumbs for you from whichever image is being painted onto each canvas.

**Comment by atomotic** [comment] 2018-05-01 19:40
i've updated `biif-cli` and regenerated the manifest (also i removed the previous thumbnails to test the automatic generation), but now i see a `TypeError: iiifResource is null`

http://universalviewer.io/uv.html?manifest=https://docuver.se/uv-app-starter/collection/0-vague-21/index.json

https://docuver.se/uv-app-starter/

thanks

**Comment by edsilv** [comment] 2018-05-01 20:48
The most up-to-date build of the UV is always at /examples. It works for me:

https://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fdocuver.se%2Fuv-app-starter%2Fcollection%2F0-vague-21%2Findex.json

It looks like the problem with https://docuver.se/uv-app-starter/ is that it's looking for your collection at https://docuver.se/collection/index.json instead of https://docuver.se/uv-app-starter/collection/index.json

Cool manifest btw!

**Comment by atomotic** [comment] 2018-05-01 21:03
i fixed `<iiif-gallery manifest="/uv-app-starter/collection/index.json"></iiif-gallery>` and i also updated `uv`

now it's working https://docuver.se/uv-app-starter/

that's great, thanks!
i've a lot of digitized zines, i'm gonna publish them all on a dedicated site very soon

**Comment by edsilv** [comment] 2018-05-01 21:21
Awesome! Let me know if I can help with anything else.

**Closed as completed by edsilv** 2018-05-01 21:21 UTC
